### ISSUE TITLE
Create minimal Java grammar for this project in order to make code less complex.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#10]
See https://github.com/www-splitcells-net/net.splitcells.network.community/blob/main/src/main/md/net/splitcells/network/community/compatibility-portability-and-adaptability/2021-03-08-create-minimal-java-grammar.md

**Comment by martins-avots** [comment]
This issue was moved to https://codeberg.org/splitcells-net/net.splitcells.network.community/issues/26
