### ISSUE TITLE
Support FlatZinc.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#111]
* [ ] Link relevant site like: https://www.minizinc.org/
* [ ] Document, that this is the main feature how interoperability for optimization is supported.
* [ ] This is also the main effort to support of modelling optimization problems as CSPs.
* [ ] Optimize problems given FlatZinc format.
* [ ] Delegate optimization by emitting problem in FlatZinc format and optimize it via a solver, that supports FlatZinc.
* [ ] Use FlatZinc in order to solve sub problems present in the constraint based repairer.
* [ ] Start competition agains other Java optimizer via Mini/FlatZinc. -> Choco Solver as main competitor
   * https://choco-solver.org/docs/considerations/
   * https://github.com/chocoteam/choco-parsers/blob/master/MINIZINC.md
- [ ] Make Gel compatible to MiniZinc.
- [ ] Find benchmarking software for MiniZinc: https://github.com/MiniZinc/mzn-bench
- [ ] Do some benchmarking.

# Ideas
* [ ] Take part in public challenges: https://www.minizinc.org/challenge2022/results2022.html
* [ ] Create permanent interaction with MiniZinc.

**Comment by martins-avots** [comment]
This issue was moved to the community repo.
