### ISSUE TITLE
Do not execute administrative commands via `package.install`.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#113]
- [ ] Create `user.package.install` command, for package managers that install a program on user level,
without admin like rights.
- [ ] Create `system.package.install`, where installation needs admin rights or installs the package system wide.
- [ ] Do not execute code via `package.install`, that need admin like rights.
Do not execute `system.package.install`.
Instead, print all known commands that solve this problem.
Otherwise, it is hard for the user to decide how things are installed.
The dependency mechanism can get sometime hard to understand.

**Comment by martins-avots** [comment]
This is not relevant for now.
