### ISSUE TITLE
Create machine learning interface.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#120]
- [ ] Integrate [dl4j](https://github.com/eclipse/deeplearning4j) for demo purposes.
This could be used for the constraint group based repair.
This th most interesting, because it is an Eclipse project.
   - [ ] Contact Eclipse people about the results.
- [ ] Try out [Deep Java Libarary](https://github.com/deepjavalibrary/djl). It may be the easier to setup, because it has ready to go network models.
      The  Multilayer Perceptron (`ai.djl.basicmodelzoo.basic.Mlp`) seems to be an easily configurable network.

**Comment by martins-avots** [comment]
This issue was moved to the community repo.
