### ISSUE TITLE
Create interactive database and allocations interface.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#121]
- [ ] Provide paths for interactive access to webserver.
- [ ] Implement interactive interface as a database:
   - [ ] That is synchronized to the actual table, in order to see changes
   - [ ] and in order to execute changes via the interface.
   - [ ] Can produce a serialization of the database.
   - [ ] Accepts addition commands as strings.
   - [ ] Accepts removal commands as strings.
- [ ] Create web GUI,
   - [ ] for database
   - [ ] and allocations, that is inspired by conflict resolution.

**Comment by martins-avots** [comment]
This is not relevant for now.
