### ISSUE TITLE
Support different backends for Gel's API.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#131]
- [ ] Use Choco-Solver as an alternative backend: https://github.com/chocoteam/choco-solver
- [ ] Support using multiple backends at once as a way to support cross framework integration.
- [ ] Inform Choco project after the implementation is completed.
- [ ] Document about theory behind transforming CSP to a assignment problem.

**Comment by martins-avots** [comment]
This issue was moved to the community repo.
