### ISSUE TITLE
Support book format in order to have a clear construction path.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#153]
* [ ] Define chapter structure concept, where the level of chapters is limited to 3-6.
   * [ ] Define goals like ensuring, that all content can be arranged in simple formats. This ensures that kinks of document format is found and makes the content portable to simple mediums.
* [ ] Define chapter merge of multiple projects.
* [ ] Implement the definition.
* [ ] Render to book folder layout and already supported file formats.
   * [ ] This makes the underlying custom software maintained by me more replaceable in the future. Also add this to general project guidelines.

# Alternative
* [ ] Define goal: convert projects to the simplest possible formats, where default rendering is widely supported.
   This may be the basis for alternative project structure, where portability/translatability is maximized,
   because no special tooling is required to render such a project (but advanced tooling can be used for improved rendering) and such tooling is widely available.
* [ ] Create a method to render every text document as a CommonMark document.
   Define CommonMark subset for set via BNF, in order to ensure portability/translatability.
* [ ] Define subset of CommonMark for XML/JSON like files.
* [ ] Render all files to the same folder, which simplifies linking.

**Comment by splitcells** [comment]
Will not be done for now.
