### ISSUE TITLE
Define Gel and Sep as file system with minimal schema.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#164]
The biggest plan for the future of this project is the goal to provide an interface for different programming paradigms,
in order to make these compatible to each other.
I suspect, that this could be used in order to get better performance:
* [ ] Theorem Proofing: translate constraint systems
* [ ] Machine Learning: generic problem interfaces for solvers based on machine learning
* [ ] file like system of tables: versioning access and storage system for data.
* [ ] interface to other optimization software via tables

How could something like this be done?
* [ ] It should be based the most generic and easy to implement interface.
Maybe shell + native file system + optional backend database in order to be portable, which is not always the case for the native file systems?
* [ ] Maybe consider OS state interface as the base for this?
* [ ] Consider creating a new subproject for this (i.e. `net.splitcells.merger`).
* [ ] Create objective and solution documentation/specification.
* [ ] Implement a primitive and somewhat complying first draft in order to test the concept a bit.
A full-blown correct implementation is not yet required.
Just a starting point is required.

**Comment by martins-avots** [comment]
This is irrelevant by now.
