### ISSUE TITLE
Create game based on optimization networks.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#170]
See blog for more details: https://splitcells-net.srht.site/net.splitcells.network.community.via.hugo/blog/2022-12-21-1-create-game-based-on-optimization-networks/

* [x] Are lookups getting too big inside constraints? -> This is just the initialization. As long as initializations do not happen regularly (i.e. because of many different values being present in a column), this is not a problem.
![image](https://github.com/www-splitcells-net/net.splitcells.network/assets/119068338/62b81f78-17bc-421f-b674-2bfd7a45f5cc)
* [ ] Provide ForAll alternative, where costs are not striped from rater, in order to get better runtime.
![image](https://github.com/www-splitcells-net/net.splitcells.network/assets/119068338/9ae1ec3c-ffee-433f-b11f-20f3430deb41)
* [x] Many small persistent lookup tables might cause longer runtimes as well. -> As long as this is not the main performance problem, this will be ignored, as a fix will probably take much effort for this.
![image](https://github.com/www-splitcells-net/net.splitcells.network/assets/119068338/9c7bcf82-9ce3-4d9e-ab35-28300251570a)
* [ ] Improve runtime of `Database#addTranslated`, because it is called many times.
![image](https://github.com/www-splitcells-net/net.splitcells.network/assets/119068338/e6f19f3d-c6ab-4642-9eb5-525bef2d29ed)
* [ ] Speed up access to line values.
![image](https://github.com/www-splitcells-net/net.splitcells.network/assets/119068338/48cea39c-671f-4f6c-a84a-0bfd0742375a)

**Comment by martins-avots** [comment]
This issue will be actived later.
