### ISSUE TITLE
Make main Gel's fluent interface complete.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#175]
* [ ] Create main interface guidelines for project.
   * [ ] Backwards compatibility guarantees
      * [ ] Make only main fluent API backwards compatible.
      * [ ] Create a naming convention for the main class, that serves as an entry point. Maybe `<ProjectName>Api`?
   * [ ] Which projects should have one.
* [ ] Add rating construction to query system.
* [ ] Document that query will be the base for future constrain language.
* [ ] Define meta API for project.

**Comment by martins-avots** [comment]
This is not relevant for now.
