### ISSUE TITLE
Make it possible to check code, licensing and dependencies automatically and locally.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#176]
* [ ] https://www.devwithimagination.com/2020/05/17/license-and-version-checks-the-manual-way-maven/
* [ ] https://wiki.52north.org/Documentation/BestPracticeLicenseManagementInSoftwareProjects
* [ ] https://www.mojohaus.org/license-maven-plugin/

**Comment by martins-avots** [comment]
This issue was moved to the community repo.
