### ISSUE TITLE
Support drop-in replacement of POSIX and other commands.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#177]
* [ ] This makes it easier to use new better tools without learning new command names or even options.
* [ ] Support drop-in replacement of cat via bat.
* [ ] Create command to start shell with this special environment.
The good thing is, that everything can be done by adjusting the PATH for the special environment.
This way, many shells can be supported.
* [ ] Maybe command shortcuts via commands is relevant here?

**Comment by martins-avots** [comment]
This is not relevant for now.
