### ISSUE TITLE
Extend constraint based repair with generic constraint based proposal method.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#180]
* [ ] Document reason for such a functionality:
   * [ ] A kind of worst case can be found at `SchoolCourseSchedulingTest#railsForSchoolSchedulingOptimization`.
It shows how costly it can get to create propsal functions manually.
   * [ ] This functionality functions like a reversal of the demandGrouping process.
* [ ] Design algorithm:
   * [ ] Select constraint paths as it is done with the GroupSelector.
   * [ ] Try out all free supplies for each demand to be repaired. This can be optimized by only trying out distinct supplies.
   * [ ] Choose one of the supplies, which have the best ratings according to the constraints selected by GroupSelector.

**Comment by martins-avots** [comment]
This was implemented for #170 .
The proposal system is used in order to prevent the solver from changing values,
which are in the past of the world.
This prevents the solver from chaning the past of the world.
