### ISSUE TITLE
Integrate logging repo into website.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#181]
This will make it easier to find and view relevant files.
* [ ] #164 should be processed first, because it is a dependency for this.
* [ ] Rendering needs to be fixed for these files.
* [ ] Some files need to be downloaded, because rendering these in browser may not be helpful (i.e. fods via Libre Office).

**Comment by martins-avots** [comment]
This is done. This network log repo.
