### ISSUE TITLE
Discover and execute OSI commands from website.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#194]
* [ ] Create web server API, that allows one to execute OSI commands via the website.
* [ ] Render all commands as a tree, in order to have a command overview.
* [ ] Render command documentation as well.

# Ideas for future
* [ ] Support command line options.
* [ ] Distinct between commands, that are intended to be executed anywhere, and commands where the current folder is part of the API.

**Comment by martins-avots** [comment]
This is not relevant for now.
