### ISSUE TITLE
Release system on FlatHub, so it can be easily installed and started.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#195]
* [ ] Create a BOM for all dependencies located in a dedicated repo, so the updates do not pollute the git history.
* [ ] Consider: https://jreleaser.org/guide/latest/configuration/packagers/flatpak.html
* [ ] Test this Flatpak on Windows WSL.
* [ ] https://docs.flathub.org/docs/for-app-authors/requirements/
* [ ] Use Jreleaser.

**Comment by martins-avots** [comment]
This issue was moved to the community repo.
