### ISSUE TITLE
Replace exceptions in core code.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#205]
* [ ] Blog about it. See https://splitcells-net.srht.site/blog/2021-10-04-there-is-bad-there-is-horrible-and-then-there-is-error-handling/ for reference.
* [ ] Exceptions are a very useful concept and helpful, but should only be used indirectly or in extension/aspect code.
   No catching in core/API code.
* [ ] Error repair should be handled via explicitly returned error values, but how to handle returned unprocessed errors?
   Probably all errors should be stored in environment and after execution it should be checked, if all errors were processed.
   When processing an error, the error is to be removed from the environment.
   It should be possible to disable this environment safeguard for increased runtime performance.
   A static boolean flag could be used in this case instead.
* [ ] See Java Thread UncaughtExceptionHandler for inspiration.

**Comment by martins-avots** [comment]
This issue is not relevant for now.
