### ISSUE TITLE
Delete all snapshot build packages regularly.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#206]
Otherwise, the used storage size will rise without limits.
* [ ] https://github.com/marketplace/actions/delete-old-packages
* [ ] https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package#deleting-a-version-of-a-repository-scoped-package-with-graphql

**Comment by martins-avots** [comment]
This is not important for now, because the version property for Maven projects is not changed in the committed code.
The version will only be changed during releases, but will not be committed,
as it makes development easier.
