### ISSUE TITLE
Ensure that all maths operations are correct.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#211]
* [ ] Document that, especially overflows caused by additions and multiplications, could be an issue.
* [ ] Wrap all such primitives via objects.
* [ ] Ban use of such primitives.

**Comment by martins-avots** [comment]
This is not important for now.

**Comment by martins-avots** [comment]
Wrapping primitive types will probably lead to performance issue.
A solution for this will be found, when such problem happens.
Before that, actions regarding this are too costly.
