### ISSUE TITLE
Process project status badges weekly.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#212]
* This is a service task of the [README](https://github.com/www-splitcells-net/net.splitcells.network.hub).
* Ensure that test coverage only rises.
    * Current: https://app.codecov.io/gh/www-splitcells-net/net.splitcells.network/tree/master/projects%2Fnet.splitcells.dem%2Fsrc%2Fmain%2Fjava%2Fnet%2Fsplitcells%2Fdem%2Flang%2Fperspective

**Comment by martins-avots** [comment]
This ticket is now processed via `https://github.com/www-splitcells-net/net.splitcells.network.community.via.hugo`.
