### ISSUE TITLE
Use Nix for Dependencies in CI and Build System

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#4]
Nix and similar package managers seem to be like the ideal package management systems
and may represent the future for Linux etc.

I want to support it and the first step is to use it in my projects.
This also serves as an valdiation of such a package manager.

- [ ] For sourcehut there is already such a CI configuration.
- [ ] For GitHub a NixOS docker image has to be used.
- [ ] For GitLab the solution is unknown.
- [ ] Provide NixOS configuration for building of this project locally.
- [ ] Provide NixOS configuration for development of this project locally.

**Comment by splitcells** [comment]
This issue waits for completion of #5 .
