### ISSUE TITLE
Host open source version of website on splitcells.net.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#59]
This way we can be sure, that the site is working.
Also, it would be nice to have the open source version to be available from the official domain.

This way it can be ensured, that the website can also be reliable hosted in subfolders on domains.
This should already work, but it is not used, so.... 😅

- [ ] Move personal website in subfolder.
- [ ] Host open source version of website.

**Comment by martins-avots** [comment]
There is another issue for that.
