### ISSUE TITLE
Improve licensing practices.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#78]
- [x] https://www.it-cisq.org/software-bill-of-materials/index.htm
- [ ] Use https://reuse.software/ in order to check licensing in source code.
   - [x] Use tmp branch for this experiment.
   - [ ] https://reuse.software/tutorial/
      - [x] `reuse init`
      - [ ] `~/.local/bin/reuse lint`
   - [ ] Document: This is provided by Free Software Foundation Europe, so it's interesting.
   - [x] The reuse-tool is licensed under the GPL-3. Is that a problem?
   - [x] Register main repo at: https://api.reuse.software/register
- [ ] Create licensing guidelines.
  - [ ] Create documentation stating all licence checks, that should be done.
  - [ ] Link to SPDX in licensing guidelines and comment its importance: https://spdx.github.io/spdx-spec/file-tags/
  - [ ] Add REUSE to licensing guidelines.
- [ ] Document/link licensing overview in README.
- [x] Add Reuse to project file system standard and document, that its LICENSES folder is exceptional.
- [ ] When rendering CommonMark files, the licence info at the start of the file should be moved to the end of the file.
- [ ] Improve licensing info on deployed website.
    - [ ] Licensing of images
    - [ ] List license of every page centrally
    - [ ] Show license of every page on every page
    - [ ] Link to `NOTICE.md` and `LICENSE.md`.
- [ ] Improve licensing parctices on every repo.

**Comment by martins-avots** [comment]
This issue was moved to the community repo.
