### ISSUE TITLE
Benchmark and profile project's performance.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#93]
- [ ] Create exemplary benchmark.
- [ ] Store results.

**Comment by martins-avots** [comment]
This is already implemented.
Note, that the time measuring currently is not very accurate.
See https://splitcells.net/net/splitcells/gel/test/functionality/NQueenProblemTest/test_8_queen_problem_with_backtracking/splitcells-XPS-15-9570.csv.html
